### PR TITLE
Add support for an ignore file

### PR DESCRIPTION
**Pull request by rickypai**
Hi rubysec folks, first of all, thanks you for the great work for this gem.

I want to add the option to support an ignore file similar to `.gitignore` like `.bundlerauditignore` (name is debatable). This way, we can more easily manage which advisories to ignore in CI systems.

Thank you,

### CODE REVIEW

**Comment by woodbusy** [comment]
I too would find this very useful. The only merge conflict at present is a simple one in README.md. It doesn't look like the maintainers are very active these days, though :(.

**Comment by mariozaizar** [comment]
👍

**Comment by ericmhalvorsen** [comment]
Seems like this has been open for a couple years now, but I would also throw in my 👍

**Comment by rickypai** [comment]
I resolved the merge conflict. be nice to get some eyes on this.

**Comment by GUI** [comment]
If it helps in verifying and testing this patch, I upgraded to @rickypai's latest version with the merge conflicts resolved, and it's working great for us across multiple projects. Thanks, @rickypai!

**Comment by kaelumania** [comment]
I find this functionality quiet useful 👍 further I would lend the ignore behaviour from brakeman, which makes an awesome job with its `brakeman.ignore`

**Comment by rickypai** [comment]
@postmodern could you please take a look? this has been around for a while

**Pull request closed without merging**
