### PR TITLE
Allow the user to specify an output filename

### PR DESCRIPTION
**Pull request by vraravam**
so that the html report can be captured in a custom location as needed. If no argument is specified, the report is generated with a default name.

### CODE REVIEW

**Comment by vraravam** [comment]
Closing

**Comment by AlexWayfer** [comment]
> Closing

Why?

**Comment by AlexWayfer** [comment]
@vraravam, please answer.

**Comment by vraravam** [comment]
Sorry - I am no longer maintaining the my fork. I was reviewing all the commits on top (for me to rebase and give a single commit for only my changes) - and it seemed that this feature/PR was no longer of use to anyone (its been 5 years and no movement) - so, rather than spending time to cleanup the PR, I just closed it.

**Comment by vraravam** [comment]
@AlexWayfer - if its really useful lets get it merged. If so, I can reopen the PR.

**Comment by AlexWayfer** [comment]
> @AlexWayfer - if its really useful lets get it merged. If so, I can reopen the PR.

OK, thank you. Right now I'm not interested in it, just curious.

**Pull request closed without merging**
