### PR TITLE
Add option for HTML output

### PR DESCRIPTION
**Pull request by JustinAiken**
# Adds HTML output

Perfect for CI!
## Example:

screenie
## Notes
- Tests are failing for me on master - same tests fail here, nothing new broken (EDIT - N/m, fail local, passed Travis)
- I haven't written any tests for the yet; I'll wait and bother if there's enough interest
- Manually chunking in the HTML is a bit clunky, but I didn't want to add any dependencies.
- HTML report is a bit ugly, if anyone w/ a bit more front end skills wants to pretty up, let me know

### CODE REVIEW

**Comment by ikarthikm** [comment]
Please merge this, would be extremely useful 🙏

**Comment by postmodern** [comment]
I'm working on a new Printers API to handle formatting of results. Input welcomed. https://github.com/rubysec/bundler-audit/compare/cli-printers?expand=1

**Comment by JustinAiken** [comment]
> I'm working on a new Printers API to handle formatting of results. Input welcomed

@postmodern - That looks fantastic! A far better approach than the brute-force hacking I did here 👍

**Comment by anym0us** [comment]
@JustinAiken any updates on this? It would be extremely useful.

**Comment by JustinAiken** [comment]
Sweet, that looks good! Do you want to open a PR with that, or should cherry-pick that into this PR?

**Comment by anym0us** [comment]
@JustinAiken,
Thanks for reply! 🙂 Please cherry-pick if it's not much effort for you.

**Comment by postmodern** [comment]
FYI with this new [bundler/audit/formats](https://github.com/rubysec/bundler-audit/blob/json-format/lib/bundler/audit/cli/formats.rb#L62) API, it will be possible to release formats as gems which bundler-audit will attempt to require via `bundler/audit/formats/#{format_name}`. I'm not sure whether bundler-audit should own the HTML format or let a 3rd party gem handle the inevitable CSS related PRs?

**Comment by JustinAiken** [comment]
>  I'm not sure whether bundler-audit should own the HTML format or let a 3rd party gem handle the inevitable CSS related PRs?

The latter makes more sense to me..

I'll close this one, and wait for a better one to come out that uses the formatting API properly. 

Personally, the company I'm out now just flat out fails CI if we have any out-of-date gems, so I don't need the HTML reports anymore 😆

**Comment by postmodern** [comment]
bundler-audit 0.8.0.rc1 has been released, and includes a new extendable [Formats API](https://github.com/rubysec/bundler-audit/blob/master/lib/bundler/audit/cli/formats.rb).

**Pull request closed without merging**
