### PR TITLE
Simplify .gemspec file

### PR DESCRIPTION
**Pull request by fatkodima**

### CODE REVIEW

**Comment by postmodern** [comment]
The `.gemspec` file is meant to load `gemspec.yml`.

**Comment by fatkodima** [comment]
@postmodern Didn't get it. Why yaml file is needed and proposed version is not working in this case?

**Comment by AlexWayfer** [comment]
> The `.gemspec` file is meant to load `gemspec.yml`.

Please, describe, why it's better.

I see in this PR `+27 −72` lines of code. And a less code is the better code.

**Comment by postmodern** [comment]
It separates the human readable gemspec metadata from the boilerplate gemspec code (ex: `git ls-files`). The boilerplate gemspec file is already 67 lines, so shortening it down even further feels like diminishing returns.

**Pull request closed without merging**
